appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: n2M2tgFc9S/xIOtGpkXg4q0v0GIyGsgFxxsQwwCbKsV625rztCQfEmxV5hYyva22vTl3G7lOZfdcuGEyhT9rBPkQqwraE8Hf//KGhXZXvgFXBevPGUmP+MweJQI/BIhfu/lDKzMj62lDINqNxuSJJkiCHa2SD1ChUGZ/gtYA4U7NvPXRkJQ3idf9a25KguvRPFCUxzjpPZA5upnMOp+KDG4xpt6jc8xaC9HFfv2k4QElPc2EfSe3hiE0+rSktuVmGT6hnHvfw0sijV8auHkNNaDGRob/1WYXxPUCEl72ZFnJ8o8x1P/H5FR+Q+m1vQBmV6u2OhqVHQzy8ed587m3EZxJyfJ9yc/2/ZU1l4aQ71bsnXO9tHQ8MsRLzFxwCCo8RWJHhc/aaLlE8i+AULjv92y2ukQ0YdqmaGIj0pdLbUJMGKN9i+MxvbMaVj6HLeFzTwqcWoFmBa1I4P8mWN9w/iZODqmjaDgQQPJcatxyoyxkkjP4AQuljz38vMcfOulaFHRMAZAu31yN0d1s7EIiKYF0php25rweMqKOtU+0bs408zCQ8MsWxCvXO+dUcnCCGfe1MPJ7EIqCptK5UU+JZKV2PqBosByU2qoyi151arEK43Dj48c3uilg2xV+z8uH0NXlZYeAWxp7Tfrwr7VDre3uV9n+Zvmno56B+lP3j44=}
